image: node:10.15.3
clone:
  depth: full
pipelines:
  branches:
    master:
      - step:
          deployment: production
          script:
            - npm install
            - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git $BITBUCKET_BRANCH
