const PORT = process.env.PORT
const MONGODB_URI = process.env.MONGODB_URI
const MONGODB_TEST_URI = process.env.MONGODB_TEST_URI
const WORKERS = process.env.WORKERS
const ACCESS_JWT_SECRET = process.env.ACCESS_JWT_SECRET
const ACCESS_JWT_LIFE_TIME = process.env.ACCESS_JWT_LIFE_TIME
const REFRESH_JWT_SECRET = process.env.REFRESH_JWT_SECRET
const REFRESH_JWT_LIFE_TIME = process.env.REFRESH_JWT_LIFE_TIME
const REDIS_URL = process.env.REDIS_URL
module.exports = {
  PORT,
  MONGODB_URI,
  MONGODB_TEST_URI,
  WORKERS,
  ACCESS_JWT_SECRET,
  ACCESS_JWT_LIFE_TIME,
  REFRESH_JWT_SECRET,
  REFRESH_JWT_LIFE_TIME,
  REDIS_URL
}
